name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

# env:
#   NODE_AUTH_TOKEN: ${{env.NODE_AUTH_TOKEN}}
#   VAR: "aaa"

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app

    steps:
      - uses: actions/checkout@v2

      # Setup Nodejs
      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 20
          registry-url: 'https://npm.pkg.github.com/adserve'   
        env:
          NODE_AUTH_TOKEN: ${{env.NODE_AUTH_TOKEN}}
          VAR: "aaa"

      
      - name: echo token
        run: echo $env.NODE_AUTH_TOKEN

      - name: echo token
        run: echo ${{env.NODE_AUTH_TOKEN}}

      # Install deps
      - name: Install deps
        run: npm install

      # Compile the code
      - name: Build project
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm run test
