name: Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app

    steps:
      - uses: actions/checkout@v2

      # Setup Nodejs
      - name: Setup Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 20

      # Install deps
      - name: Install deps
        run: npm install

      # Compile the code
      - name: Build project
        run: npm run build

      # Run tests
      - name: Run tests
        run: npm run test
